# ç½‘ç«™çš„åŸºæœ¬ä¿¡æ¯
site:
  tab: Kumo's Blog # æµè§ˆå™¨æ ‡ç­¾æ ä¸Šæ˜¾ç¤ºçš„æ–‡æœ¬
  title: ğŸ’  Frosti # ç½‘ç«™çš„æ ‡é¢˜
  description: A clean, elegant, and fast static blog template! ğŸš€ Developed with Astro # ç½‘ç«™çš„æè¿°ï¼Œç”¨äºSEOç­‰
  language: zh # ç½‘ç«™çš„è¯­è¨€ï¼Œä¾‹å¦‚ "en" æ˜¯è‹±æ–‡
  favicon: /favicon.ico # ç½‘ç«™çš„å›¾æ ‡ï¼Œç”¨äºæµè§ˆå™¨æ ‡ç­¾æ å’Œå…¶ä»–åœ°æ–¹æ˜¾ç¤º
  theme: # æ›´å¤šä¸»é¢˜ https://daisyui.com/docs/themes/
    light: winter # ä¸»é¢˜çš„æµ…è‰²æ¨¡å¼
    dark: dracula # ä¸»é¢˜çš„æ·±è‰²æ¨¡å¼
    code: github-dark # ä»£ç å—çš„ä¸»é¢˜ https://expressive-code.com/guides/themes/
  date_format: ddd MMM DD YYYY # æ—¥æœŸæ ¼å¼è®¾ç½®ï¼Œæ”¯æŒè‡ªå®šä¹‰æ ¼å¼
  blog: # åšå®¢ç›¸å…³é…ç½®
    pageSize: 8 # æ¯é¡µæ˜¾ç¤ºçš„æ–‡ç« æ•°é‡
  menu: # èœå•é…ç½®
    - id: home # èœå•é¡¹çš„å”¯ä¸€æ ‡è¯†ç¬¦
      text: ä¸»é¡µ # èœå•é¡¹æ˜¾ç¤ºçš„æ–‡æœ¬
      href: / # èœå•é¡¹é“¾æ¥çš„åœ°å€
      svg: "material-symbols:home-outline-rounded"
      target: _self
    - id: about
      text: å…³äº
      href: /about
      svg: "material-symbols:info-outline-rounded"
      target: _self
    - id: blog
      text: åšå®¢
      href: /blog
      svg: "material-symbols:book-2-outline-rounded"
      target: _self
      subItems:
        - id: all
          text: å…¨éƒ¨æ–‡ç« 
          href: /blog
          svg: "material-symbols:ink-pen-outline-rounded"
          target: _self
        - id: documentation
          text: æ–‡æ¡£
          href: /blog/category/Documentation
          svg: "material-symbols:unknown-document-outline-rounded"
          target: _self
        - id: examples
          text: ç¤ºä¾‹
          href: /blog/category/Examples
          svg: "material-symbols:deployed-code-outline"
          target: _self
    - id: project
      text: é¡¹ç›®
      href: /project
      svg: "material-symbols:code-blocks-outline"
      target: _self
    - id: friend
      text: å‹é“¾
      href: /friend
      svg: "material-symbols:supervisor-account-outline-rounded"
      target: _self
    - id: contact
      text: è”ç³»
      href: "mailto:contact.evesunmaple@outlook.com"
      target: _blank
      svg: "material-symbols:attach-email-outline-rounded"

# ç”¨æˆ·çš„ä¸ªäººä¿¡æ¯
user:
  name: KumoMayu # ç”¨æˆ·å
  site: "https://kumomayu.pages.dev" # ç”¨æˆ·çš„ç½‘ç«™é“¾æ¥
  avatar: /profile.png # ç”¨æˆ·å¤´åƒè·¯å¾„
  sidebar:
    social:
      - href: "https://github.com/KumoMayu"
        ariaLabel: Github
        title: Github
        svg: "ri:github-line"

      - href: "https://space.bilibili.com/1636083563"
        ariaLabel: BiliBili
        title: BiliBili
        svg: "ri:bilibili-line"

      - href: "https://www.xiaohongshu.com/user/profile/64760333000000002a0366c2"
        ariaLabel: Xiaohongshu
        title: Xiaohongshu
        svg: "simple-icons:xiaohongshu"

      - href: "https://www.instagram.com/ng_tungho/"
        ariaLabel: Instagram
        title: Instagram
        svg: "ri:instagram-line"

      - href: "https://tuxun.fun/user/70581"
        ariaLabel: Tuxun
        title: Tuxun
        svg: "ri:earth-line"

  footer:
    social:
      - href: "https://github.com/KumoMayu"
        ariaLabel: Github
        title: Github
        svg: "ri:github-line"

      - href: "https://space.bilibili.com/1636083563"
        ariaLabel: BiliBili
        title: BiliBili
        svg: "ri:bilibili-line"

      - href: "https://www.xiaohongshu.com/user/profile/64760333000000002a0366c2"
        ariaLabel: Xiaohongshu
        title: Xiaohongshu
        svg: "simple-icons:xiaohongshu"

      - href: "https://www.instagram.com/ng_tungho/"
        ariaLabel: Instagram
        title: Instagram
        svg: "ri:instagram-line"

      - href: "https://tuxun.fun/user/70581"
        ariaLabel: Tuxun
        title: Tuxun
        svg: "ri:earth-line"
